/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppTeachersRouteImport } from './routes/_app.teachers'
import { Route as AppSubstitutionsRouteImport } from './routes/_app.substitutions'
import { Route as AppSubjectsRouteImport } from './routes/_app.subjects'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppScheduleRouteImport } from './routes/_app.schedule'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppLessonsRouteImport } from './routes/_app.lessons'
import { Route as AppGeneratorRouteImport } from './routes/_app.generator'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConstraintsRouteImport } from './routes/_app.constraints'
import { Route as AppClassroomsRouteImport } from './routes/_app.classrooms'
import { Route as AppClassesRouteImport } from './routes/_app.classes'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeachersRoute = AppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppRoute,
} as any)
const AppSubstitutionsRoute = AppSubstitutionsRouteImport.update({
  id: '/substitutions',
  path: '/substitutions',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsRoute = AppSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonsRoute = AppLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AppRoute,
} as any)
const AppGeneratorRoute = AppGeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConstraintsRoute = AppConstraintsRouteImport.update({
  id: '/constraints',
  path: '/constraints',
  getParentRoute: () => AppRoute,
} as any)
const AppClassroomsRoute = AppClassroomsRouteImport.update({
  id: '/classrooms',
  path: '/classrooms',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
    '/schools': typeof SchoolsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AppAnalyticsRoute
  '/classes': typeof AppClassesRoute
  '/classrooms': typeof AppClassroomsRoute
  '/constraints': typeof AppConstraintsRoute
  '/dashboard': typeof AppDashboardRoute
  '/generator': typeof AppGeneratorRoute
  '/lessons': typeof AppLessonsRoute
  '/notifications': typeof AppNotificationsRoute
  '/reports': typeof AppReportsRoute
  '/schedule': typeof AppScheduleRoute
  '/settings': typeof AppSettingsRoute
  '/subjects': typeof AppSubjectsRoute
  '/substitutions': typeof AppSubstitutionsRoute
  '/teachers': typeof AppTeachersRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AppAnalyticsRoute
  '/classes': typeof AppClassesRoute
  '/classrooms': typeof AppClassroomsRoute
  '/constraints': typeof AppConstraintsRoute
  '/dashboard': typeof AppDashboardRoute
  '/generator': typeof AppGeneratorRoute
  '/lessons': typeof AppLessonsRoute
  '/notifications': typeof AppNotificationsRoute
  '/reports': typeof AppReportsRoute
  '/schedule': typeof AppScheduleRoute
  '/settings': typeof AppSettingsRoute
  '/subjects': typeof AppSubjectsRoute
  '/substitutions': typeof AppSubstitutionsRoute
  '/teachers': typeof AppTeachersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/classes': typeof AppClassesRoute
  '/_app/classrooms': typeof AppClassroomsRoute
  '/_app/constraints': typeof AppConstraintsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/generator': typeof AppGeneratorRoute
  '/_app/lessons': typeof AppLessonsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/schedule': typeof AppScheduleRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/subjects': typeof AppSubjectsRoute
  '/_app/substitutions': typeof AppSubstitutionsRoute
  '/_app/teachers': typeof AppTeachersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/analytics'
    | '/classes'
    | '/classrooms'
    | '/constraints'
    | '/dashboard'
    | '/generator'
    | '/lessons'
    | '/notifications'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/subjects'
    | '/substitutions'
    | '/teachers'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/analytics'
    | '/classes'
    | '/classrooms'
    | '/constraints'
    | '/dashboard'
    | '/generator'
    | '/lessons'
    | '/notifications'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/subjects'
    | '/substitutions'
    | '/teachers'
    | '/auth/callback'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_app/analytics'
    | '/_app/classes'
    | '/_app/classrooms'
    | '/_app/constraints'
    | '/_app/dashboard'
    | '/_app/generator'
    | '/_app/lessons'
    | '/_app/notifications'
    | '/_app/reports'
    | '/_app/schedule'
    | '/_app/settings'
    | '/_app/subjects'
    | '/_app/substitutions'
    | '/_app/teachers'
    | '/auth/callback'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/teachers': {
      id: '/_app/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AppTeachersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/substitutions': {
      id: '/_app/substitutions'
      path: '/substitutions'
      fullPath: '/substitutions'
      preLoaderRoute: typeof AppSubstitutionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subjects': {
      id: '/_app/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AppSubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lessons': {
      id: '/_app/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof AppLessonsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/generator': {
      id: '/_app/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof AppGeneratorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/constraints': {
      id: '/_app/constraints'
      path: '/constraints'
      fullPath: '/constraints'
      preLoaderRoute: typeof AppConstraintsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/classrooms': {
      id: '/_app/classrooms'
      path: '/classrooms'
      fullPath: '/classrooms'
      preLoaderRoute: typeof AppClassroomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/classes': {
      id: '/_app/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppClassesRoute: typeof AppClassesRoute
  AppClassroomsRoute: typeof AppClassroomsRoute
  AppConstraintsRoute: typeof AppConstraintsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGeneratorRoute: typeof AppGeneratorRoute
  AppLessonsRoute: typeof AppLessonsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubjectsRoute: typeof AppSubjectsRoute
  AppSubstitutionsRoute: typeof AppSubstitutionsRoute
  AppTeachersRoute: typeof AppTeachersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppClassesRoute: AppClassesRoute,
  AppClassroomsRoute: AppClassroomsRoute,
  AppConstraintsRoute: AppConstraintsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGeneratorRoute: AppGeneratorRoute,
  AppLessonsRoute: AppLessonsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubjectsRoute: AppSubjectsRoute,
  AppSubstitutionsRoute: AppSubstitutionsRoute,
  AppTeachersRoute: AppTeachersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
    SchoolsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
